### ISSUE TITLE
QR Code too old?

### ISSUE THREAD

**Issue by andrejohansson** [bankid4keycloak/bankid4keycloak#19]
**Describe the bug**
Very new to this but, I've managed to do the following:

1. Installed KeyCloak 15 standalone on windows
1. Installed bankid4keycloak as a provider
1. Configured test bankid
1. Created a test realm and tried to login
1. Had to fix an issue in `login-bankid.ftl` and remove `displayWide=false` because I got a template error
1. Finally the bankid login page shows
1. I activate qr code
1. QR code shows when logging in, but I cannot use my mobile bankid to login, I get the error "QR-koden är ogiltig eftersom den är för gammal." 

Side notes:
- I have downloaded the test-bankid app from https://www.bankid.com/utvecklare/test and (which seems to overwrite my normal bankid but doesnt seem to be any different?).
- I tried to generate a test bank id from https://demo.bankid.com/ but when I'm trying to activate I get "Aktivering avbruten"

Any ideas what I might be dowing wrong?

**Comment by ullgren** [comment]
Thanks for the report. I do not have any immediate ideas about what the problem could be 
But I will try to recreate the issue and get back to you.

**Comment by ullgren** [comment]
Committed the template PR (#18 ) a fix for Keycloak 15 compliance (3dc621cf59f366f96ff03391fa0b282c9fb223e0).
Verified that the login now works both with and without QR code.

Could you please rebuild with the latest source and retry the scenario ?

**Comment by isrjo** [comment]
I'm able to reproduce the problem using the 'real' BankID client (read not the test version) whereas with the test client the QR-code works fine. This suggests you've been unable to replace the client. Since a real working BankID is required to obtain a testID two separate devices might be a good suggestion?

Over at https://demo.bankid.com/ you can both create and try out a testID.

Best of luck..

**Comment by andrejohansson** [comment]
Sorry I'm late to the party....

- I can confirm that I had used the wrong bankid client
- I can now see the qr code
- I can scan it using the test app and enter my pin
- It seems that I get verified, then I get an error in keycloak on the server side:

   ```
   12:08:59,707 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-17) Uncaught server error: java.lang.NoSuchMethodError: org.keycloak.broker.provider.BrokeredIdentityContext.setCode(Ljava/lang/String;)V
        at org.keycloak.broker.bankid.BankidEndpoint.done(BankidEndpoint.java:176)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
   ```

You can see my test setup here:
![image](https://user-images.githubusercontent.com/2828428/143014225-359b5c48-bff6-4868-b747-e87f9d0c305f.png)
